# Generated by Django 4.2 on 2023-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.CharField(default='RO, Geyser', max_length=256),
        ),
    ]
