# Generated by Django 4.2 on 2023-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0002_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1),
        ),
    ]
