# Generated by Django 4.2 on 2023-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0003_property_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
