# Generated by Django 4.2 on 2023-04-23 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0005_user_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 4, 23, 10, 28, 16, 231370)),
        ),
    ]
