# Generated by Django 4.2 on 2023-04-23 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyapp', '0007_otp_remove_user_otp_remove_user_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 11, 28, 34, 406550)),
        ),
    ]
